### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by skn123** [avaneev/avir#1]
Hi, Can you please provide an example of how to use this code? Maybe you can use "imresize.exe" as a test case.

**Comment by avaneev** [comment]
Example:

#include "avir.h"
avir :: CImageResizer<> ImageResizer( 8 );
ImageResizer.resizeImage( InBuf, 640, 480, 0, OutBuf, 1024, 768, 3, 0 );

**Comment by skn123** [comment]
Thanks Aleksey. However, is there an API that will also give us the ability to add the "--low-ringing" feature like you have in imresize?

**Comment by avaneev** [comment]
To use low-ringing mode, add these lines:
avir :: CImageResizerParamsLR ParamsLR;
avir :: CImageResizer<> ImageResizer( 8, 0, ParamsLR );

**Comment by HanYang1013** [comment]
Should I define InBuf and OutBuf by my self? like read an image into buffer using ifstream?  Because I tried your code(pretty awesome!), but it shows InBuf is not defined, and I used ifstearm to read image into buffer, but OutBuf is hard to define and cause an error. Like attached.

<img width="728" alt="screen shot 2016-12-01 at 15 18 35" src="https://cloud.githubusercontent.com/assets/8672115/20815061/9115b48a-b7d9-11e6-92a4-fb7d875c4288.png">
<img width="752" alt="screen shot 2016-12-01 at 15 19 18" src="https://cloud.githubusercontent.com/assets/8672115/20815062/91183ca0-b7d9-11e6-9734-0e450167355b.png">

**Comment by avaneev** [comment]
Yes, you should provide the buffers. Note that the type of buffers is important - it should be uint8_t* not char*. Include <stdint.h>

**Comment by HanYang1013** [comment]
Thank you for replying~ 

But I read image using ifstream and then get a char* array called imagebuffer. 
I convert char * to uint8_t * by using 
`uint8_t * inputBuffer = new uint8_t [imageLength + 1];` 
`inputBuffer = reinterpret_cast<uint8_t *>(imagebuffer);`
and I define output buffer same size with input size because I want to make image smaller.

`ImageResizer.resizeImage(inputBuffer, 4032, 3020 , 0, outputBuffer, 1040, 768, 3, 0 );`
Above is what I passed in your program, but I get error as below in packScanline() function:
![image](https://cloud.githubusercontent.com/assets/8672115/20849266/2b223706-b893-11e6-9acd-6945d3f89551.png)

I don't know what was wrong. Did I convert char * to uint8_t* wrong? or something else was wrong..

Thank you in advance~

**Comment by avaneev** [comment]
Make sure your buffer sizes are correct, and you are actually processing 3-channel image.

**Comment by shlyakpavel** [comment]
@hanyang1013 how did you finally solve the problem?
